apiRules:
- include: # The namespaces to generate
    uidRegex: ^Doji\.AI\.Safetensors
    type: Namespace
- include:
    uidRegex: ^Global
    type: Namespace
- exclude:
    uidRegex: ^Doji\.AI\.Safetensors\.Editor
- exclude:
    uidRegex: ^Doji\.AI\.Safetensors\.Samples